import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Background from "./components/Background";
import Menu from "./components/menu";



const PPul = localFont({
    src: "../public/ppul.otf",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`w-screen h-full ${PPul.className} text-4xl antialiased`}>
                <Menu />
                {children}
            </body>
        </html>
    );
}


