import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="bg-[#EBF0F8] text-gray-800 text-[14px] min-h-screen">
					<img src='/left.png' className="fixed h-screen top-0 left-0 pointer-events-none" alt="left branch" />
					<img src='/right.png' className="fixed h-screen top-0 right-0 pointer-events-none" alt="right branch" />

					{children}
				</div>
			</body>
		</html>
	);
}
